#! /bin/bash

set -eu -o pipefail
shopt -s extglob
shopt -s nullglob

reponame=sigrok
REPO_BRANCH=repo
REPO="$HOME/g/sigrok-repo"
MAKEPKG_CONF=/etc/makepkg.conf
PKGBUILD_DIR="$(dirname "$0")/.."

e () {
	printf "%s\n" "$*" >>/dev/stderr
}

die () {
	printf "%s\n" "$*"
}

if ! [ -d "$REPO" ]; then
	die "repo $REPO does not exist"
fi

. "$MAKEPKG_CONF"

mkdir -p "$REPO/$CARCH"

db_base="$REPO/$CARCH/$reponame.db"
db_full="$db_base".tar.xz

for pkgbuild in $PKGBUILD_DIR/*/PKGBUILD; do
	echo ">>> $pkgbuild"
	pushd "$(dirname "$pkgbuild")" >/dev/null
	makepkg -i --noconfirm || { e "makepkg of $pkgbuild failed, skipping"; continue; }
	. "$(basename "$pkgbuild")"
	PKG="$pkgname-$pkgver-$pkgrel-$CARCH$PKGEXT"
	cp "$PKG" "$REPO/$CARCH/"
	repo-add "$db_full" "$REPO/$CARCH/$PKG"
	popd >/dev/null
done

# repo-add creates symlinks, github raw doesn't work with symlinks
rm "$db_base"
ln "$db_full" "$db_base"

pkgbuild_ver="$(git -C "$PKGBUILD_DIR" describe --always)"
git -C "$REPO" add -A .
git -C "$REPO" commit -m "Sync to $pkgbuild_ver"
git -C "$REPO" push origin repo
